server {
    listen 80 reuseport;
    listen [::]:80 reuseport;

    server_name _;

    ################# 生产环境 ##################

    # return 403;

    ################# 测试环境 ##################

    root /var/www/default;
    index index.php index.html;

    location ~ [^/]\.php(/|$) {
        fastcgi_pass php:9000;
        include fastcgi.conf;
        include fastcgi-php.conf;
    }

    include /etc/nginx/rewrite/general.conf;
    include /etc/nginx/rewrite/security.conf;

    ############################################
}
