server {
    listen 80;
    listen [::]:80;

    server_name _;

    ################# 生产环境 ##################

    # return 403;

    ################# 测试环境 ##################

    root /var/www/default;
    index phpinfo.php;

    location ~ [^/]\.php(/|$) {
        fastcgi_pass php:9000;
        include fastcgi-php.conf;
        include fastcgi_params;
    }

    include /etc/nginx/rewrite/general.conf;
    include /etc/nginx/rewrite/security.conf;

    ############################################
}
