server {
    listen 8080 reuseport;
    listen [::]:8080 reuseport;

    server_name _;

    root /var/www/html;
    index index.php;

    location ~ [^/]\.php(/|$) {
        fastcgi_pass phpmyadmin:9000;
        include fastcgi-php.conf;
        include fastcgi_params;
    }

    include /etc/nginx/rewrite/general.conf;
    include /etc/nginx/rewrite/security.conf;
}
