FROM php:8.4-fpm-alpine

RUN sed -i "s/dl-cdn.alpinelinux.org/mirrors.cloud.tencent.com/g" /etc/apk/repositories

RUN apk update && apk --no-cache add imagemagick imagemagick-dev && rm -rf /var/cache/apk/*

ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN install-php-extensions redis memcached opcache pdo_mysql mysqli zip gd imagick igbinary bz2 exif bcmath intl
