main:
  # 每次提交同步仓库到 GitHub
  push:
    - name: 同步仓库到 GitHub
      imports:
        - https://cnb.cool/seatonjiang/secret-key/-/blob/main/github.yaml
      stages:
        - name: 同步仓库
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/seatonjiang/monolith.git
            auth_type: https
            username: ${GITHUB_USERNAME}
            password: ${GITHUB_ACCESS_TOKEN}

  # 每月构建 PHP 8.1 镜像
  "crontab: 40 14 24 * *":
    - name: 构建 PHP 8.1 AMD64
      runner:
        tags: cnb:arch:amd64
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/php:8.1-fpm-alpine-linux-amd64
      stages:
        - name: 登录制品库
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: 构建镜像
          script: docker build -t ${IMAGE_TAG} -f ./.cnb/dockerfile-php-8.1 .
        - name: 推送镜像
          script: docker push ${IMAGE_TAG}
        - name: 构建完成
          type: cnb:resolve
          options:
            key: build-php81-amd64

    - name: 构建 PHP 8.1 ARM64
      runner:
        tags: cnb:arch:arm64:v8
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/php:8.1-fpm-alpine-linux-arm64
      stages:
        - name: 登录制品库
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: 构建镜像
          script: docker build -t ${IMAGE_TAG} -f ./.cnb/dockerfile-php-8.1 .
        - name: 推送镜像
          script: docker push ${IMAGE_TAG}
        - name: 构建完成
          type: cnb:resolve
          options:
            key: build-php81-arm64

    - name: 合并 PHP 8.1 AMD64 和 ARM64
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/php:8.1-fpm-alpine
      stages:
        - name: 等待 AMD64 构建完成
          type: cnb:await
          options:
            key: build-php81-amd64
        - name: 等待 ARM64 构建完成
          type: cnb:await
          options:
            key: build-php81-arm64
        - name: 合并镜像
          image: cnbcool/manifest
          settings:
            target: ${IMAGE_TAG}
            template: ${IMAGE_TAG}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        - name: 删除临时镜像
          type: artifact:remove-tag
          options:
            name: ${REPO_NAME}/php
            tags:
              - 8.1-fpm-alpine-linux-amd64
              - 8.1-fpm-alpine-linux-arm64
            type: docker

  # 每月构建 PHP 8.2 镜像
  "crontab: 41 14 24 * *":
    - name: 构建 PHP 8.2 AMD64
      runner:
        tags: cnb:arch:amd64
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/php:8.2-fpm-alpine-linux-amd64
      stages:
        - name: 登录制品库
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: 构建镜像
          script: docker build -t ${IMAGE_TAG} -f ./.cnb/dockerfile-php-8.2 .
        - name: 推送镜像
          script: docker push ${IMAGE_TAG}
        - name: 构建完成
          type: cnb:resolve
          options:
            key: build-php82-amd64

    - name: 构建 PHP 8.2 ARM64
      runner:
        tags: cnb:arch:arm64:v8
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/php:8.2-fpm-alpine-linux-arm64
      stages:
        - name: 登录制品库
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: 构建镜像
          script: docker build -t ${IMAGE_TAG} -f ./.cnb/dockerfile-php-8.2 .
        - name: 推送镜像
          script: docker push ${IMAGE_TAG}
        - name: 构建完成
          type: cnb:resolve
          options:
            key: build-php82-arm64

    - name: 合并 PHP 8.2 AMD64 和 ARM64
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/php:8.2-fpm-alpine
      stages:
        - name: 等待 AMD64 构建完成
          type: cnb:await
          options:
            key: build-php82-amd64
        - name: 等待 ARM64 构建完成
          type: cnb:await
          options:
            key: build-php82-arm64
        - name: 合并镜像
          image: cnbcool/manifest
          settings:
            target: ${IMAGE_TAG}
            template: ${IMAGE_TAG}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        - name: 删除临时镜像
          type: artifact:remove-tag
          options:
            name: ${REPO_NAME}/php
            tags:
              - 8.2-fpm-alpine-linux-amd64
              - 8.2-fpm-alpine-linux-arm64
            type: docker

  # 每月构建 PHP 8.3 镜像
  "crontab: 42 14 24 * *":
    - name: 构建 PHP 8.3 AMD64
      runner:
        tags: cnb:arch:amd64
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/php:8.3-fpm-alpine-linux-amd64
      stages:
        - name: 登录制品库
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: 构建镜像
          script: docker build -t ${IMAGE_TAG} -f ./.cnb/dockerfile-php-8.3 .
        - name: 推送镜像
          script: docker push ${IMAGE_TAG}
        - name: 构建完成
          type: cnb:resolve
          options:
            key: build-php83-amd64

    - name: 构建 PHP 8.3 ARM64
      runner:
        tags: cnb:arch:arm64:v8
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/php:8.3-fpm-alpine-linux-arm64
      stages:
        - name: 登录制品库
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: 构建镜像
          script: docker build -t ${IMAGE_TAG} -f ./.cnb/dockerfile-php-8.3 .
        - name: 推送镜像
          script: docker push ${IMAGE_TAG}
        - name: 构建完成
          type: cnb:resolve
          options:
            key: build-php83-arm64

    - name: 合并 PHP 8.3 AMD64 和 ARM64
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/php:8.3-fpm-alpine
      stages:
        - name: 等待 AMD64 构建完成
          type: cnb:await
          options:
            key: build-php83-amd64
        - name: 等待 ARM64 构建完成
          type: cnb:await
          options:
            key: build-php83-arm64
        - name: 合并镜像
          image: cnbcool/manifest
          settings:
            target: ${IMAGE_TAG}
            template: ${IMAGE_TAG}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        - name: 删除临时镜像
          type: artifact:remove-tag
          options:
            name: ${REPO_NAME}/php
            tags:
              - 8.3-fpm-alpine-linux-amd64
              - 8.3-fpm-alpine-linux-arm64
            type: docker

  # 每月构建 PHP 8.4 镜像
  "crontab: 43 14 24 * *":
    - name: 构建 PHP 8.4 AMD64
      runner:
        tags: cnb:arch:amd64
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/php:8.4-fpm-alpine-linux-amd64
      stages:
        - name: 登录制品库
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: 构建镜像
          script: docker build -t ${IMAGE_TAG} -f ./.cnb/dockerfile-php-8.4 .
        - name: 推送镜像
          script: docker push ${IMAGE_TAG}
        - name: 构建完成
          type: cnb:resolve
          options:
            key: build-php84-amd64

    - name: 构建 PHP 8.4 ARM64
      runner:
        tags: cnb:arch:arm64:v8
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/php:8.4-fpm-alpine-linux-arm64
      stages:
        - name: 登录制品库
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: 构建镜像
          script: docker build -t ${IMAGE_TAG} -f ./.cnb/dockerfile-php-8.4 .
        - name: 推送镜像
          script: docker push ${IMAGE_TAG}
        - name: 构建完成
          type: cnb:resolve
          options:
            key: build-php84-arm64

    - name: 合并 PHP 8.4 AMD64 和 ARM64
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/php:8.4-fpm-alpine
      stages:
        - name: 等待 AMD64 构建完成
          type: cnb:await
          options:
            key: build-php84-amd64
        - name: 等待 ARM64 构建完成
          type: cnb:await
          options:
            key: build-php84-arm64
        - name: 合并镜像
          image: cnbcool/manifest
          settings:
            target: ${IMAGE_TAG}
            template: ${IMAGE_TAG}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        - name: 删除临时镜像
          type: artifact:remove-tag
          options:
            name: ${REPO_NAME}/php
            tags:
              - 8.4-fpm-alpine-linux-amd64
              - 8.4-fpm-alpine-linux-arm64
            type: docker

  # 每月构建 OpenResty 镜像
  "crontab: 54 16 24 * *":
    - name: 构建 OpenResty AMD64
      runner:
        tags: cnb:arch:amd64
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/openresty:alpine-linux-amd64
      stages:
        - name: 登录制品库
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: 构建镜像
          script: docker build -t ${IMAGE_TAG} -f ./.cnb/dockerfile-openresty .
        - name: 推送镜像
          script: docker push ${IMAGE_TAG}
        - name: 构建完成
          type: cnb:resolve
          options:
            key: build-openresty-amd64

    - name: 构建 OpenResty ARM64
      runner:
        tags: cnb:arch:arm64:v8
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/openresty:alpine-linux-arm64
      stages:
        - name: 登录制品库
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: 构建镜像
          script: docker build -t ${IMAGE_TAG} -f ./.cnb/dockerfile-openresty .
        - name: 推送镜像
          script: docker push ${IMAGE_TAG}
        - name: 构建完成
          type: cnb:resolve
          options:
            key: build-openresty-arm64

    - name: 合并 OpenResty AMD64 和 ARM64
      services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/openresty:alpine
      stages:
        - name: 等待 AMD64 构建完成
          type: cnb:await
          options:
            key: build-openresty-amd64
        - name: 等待 ARM64 构建完成
          type: cnb:await
          options:
            key: build-openresty-arm64
        - name: 合并镜像
          image: cnbcool/manifest
          settings:
            target: ${IMAGE_TAG}
            template: ${IMAGE_TAG}-OS-ARCH
            platforms:
              - linux/amd64
              - linux/arm64
        - name: 删除临时镜像
          type: artifact:remove-tag
          options:
            name: ${REPO_NAME}/openresty
            tags:
              - alpine-linux-amd64
              - alpine-linux-arm64
            type: docker
