name: "同步代码到镜像仓库"

on:
  push:
    branches: [main]
  workflow_run:
    workflows:
      [
        "构建 Caddy 镜像",
        "构建 PHP 8.3 镜像",
        "构建 PHP 8.4 镜像",
        "添加 Docker 镜像",
        "更新 Docker 镜像",
      ]
    types:
      - completed

jobs:
  sync-repository-mirror:
    name: "同步代码到镜像仓库"
    runs-on: ubuntu-latest

    steps:
      - name: "拉取代码"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "同步代码到 CNB 仓库"
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL="https://cnb.cool/${{ github.repository }}.git" \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME="cnb" \
            -e PLUGIN_PASSWORD=${{ secrets.CNB_SYNC_TOKEN }} \
            -e PLUGIN_PUSH_TAGS="true" \
            -e PLUGIN_FORCE="true" \
            tencentcom/git-sync
